#include <iostream>
#include <Windows.h>

using std::cout;
using std::endl;

void TextColor(int font, int backGround);

void main()
{
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	cout << "¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡à";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡à";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡à¡à";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(7, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(7, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	cout << "¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	cout << "¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à";
	TextColor(7, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à";
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à";
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	cout << "¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	cout << "¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à";
	TextColor(4, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à";
	TextColor(14, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
	cout << "¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à¡à" << endl;
}

void TextColor(int font, int backGround)
{
	int Color = font + backGround * 16;
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), Color);
}