#include <iostream>
#include <Windows.h>

using std::cout;
using std::endl;

void TextColor(int font, int backGround);

void main()
{
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	cout << "¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(0, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡¡";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡¡";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(7, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(7, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	cout << "¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	cout << "¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡";
	TextColor(7, 0);
	cout << "¡á¡á¡á";
	TextColor(10, 0);
	cout << "¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	cout << "¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	cout << "¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	cout << "¡á¡á";
	TextColor(10, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	cout << "¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á";
	TextColor(7, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡";
	TextColor(4, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(2, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(12, 0);
	cout << "¡á";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(4, 0);
	cout << "¡á¡á¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(6, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(14, 0);
	cout << "¡á";
	TextColor(12, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡";
	TextColor(14, 0);
	cout << "¡á¡á¡á¡á¡á";
	TextColor(15, 0);
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
	cout << "¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡" << endl;
}

void TextColor(int font, int backGround)
{
	int Color = font + backGround * 16;
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), Color);
}